### ISSUE TITLE
为什么在accept(e,v)中会出现e==t.a_e?

### ISSUE THREAD

**Issue by Sun1Plus** [turingcell/paxos-made-easy#1]
请教大佬，只有Acceptor初始为0或者完成了PA（）之后才会t.p_e==t.a_e为true，其他情况不都是t.p_e>t.a_e吗？那为什么在accept(e,v)代码中还会有e==t.a_e？

**Comment by hnes** [comment]
@Sun1Plus 你好，实在抱歉没有能及时地看到这个Issue。

> 只有Acceptor初始为0或者完成了PA（）之后才会t.p_e==t.a_e为true，其他情况不都是t.p_e>t.a_e吗？

确实是这样子的。

> 那为什么在accept(e,v)代码中还会有e==t.a_e？

这是因为在伪代码中，考虑了更一般的情形--RPC请求P和A可能会出现duplication的情况。

这样的话，在msg不会duplication情形下的`PA`，跑到msg可能会duplication的情况下就变成了`PAAA...`（用正则表示即`PA+`）。

之所以会出现上述问题，是因为这篇文章在初稿的时候考虑了msg duplication的情况，而在后面的更新中为了简洁就把msg duplication的情况在主证明中给去掉了，但是更新的时候漏掉了此处代码的同步。尽管此时的代码依然是正确的，但确实容易使人困惑。后面我会提交一次更改解决掉这个问题。

非常感谢！
